### ISSUE TITLE
DataPackage Viewer: content of README.md included in page unescaped

### ISSUE THREAD

**Issue by morty** [frictionlessdata/ideas#190]
The content of the README.md is included in the page without being escaped.

e.g.

http://data.okfn.org/tools/view?url=http%3A%2F%2Fmorty.co.uk%2Fdatapackage.json

**Comment by rgrp** [comment]
@morty good point and i imagine that is security issue there ;-)

This should be a relatively easy fix in that it just requires us to escape when we process the README - my guess is the actual bug here is in https://github.com/okfn/datapackage-read esp https://github.com/okfn/datapackage-read/blob/master/datapackage-read.js#L111

**Comment by rgrp** [comment]
This issue was moved to okfn/datapackage-render-js#13
